spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;LOCK_MODE=0
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keep the H2 console enabled and bound to the matching path
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security Rule: Allow the H2 console layout frames to open inside modern web browsers
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false
